@startuml

interface EstrategiaPonderacion {
 +Calcular()
 +Aplica()
 +Nombre()
 +Prioridad()
}

class Contexto

class ReglaCienciasInvestigacion
class ReglaDirectorGestion
class ReglaAntiguedad
class ReglaCoordinadorAcademica
class ReglaAdministracionGestion

class Docente
class Competencia
class Evaluacion

EstrategiaPonderacion <|.. ReglaCienciasInvestigacion
EstrategiaPonderacion <|.. ReglaDirectorGestion
EstrategiaPonderacion <|.. ReglaAntiguedad
EstrategiaPonderacion <|.. ReglaCoordinadorAcademica
EstrategiaPonderacion <|.. ReglaAdministracionGestion

Contexto *-- Docente
Contexto *-- Competencia
Contexto *-- Evaluacion

@enduml